export const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "VARELLI",
  alternateName: "VARELLI Intelligent Living",
  url: "https://varelli.co.in",
  logo: {
    "@type": "ImageObject",
    url: "https://varelli.co.in/images/varelli-logo.png",
    width: 300,
    height: 60,
  },
  description:
    "VARELLI designs and engineers intelligent residential environments for luxury villas, estates and private residences across India. Specialists in KNX home automation, Dolby Atmos private cinema, Zehnder fresh air ventilation, central vacuum, and smart security - using exclusively European-origin hardware from Basalte (Belgium), Ekinex (Italy), Sonus Faber (Italy), Zehnder (Switzerland), and KNX (Germany).",
  telephone: "+919964984695",
  email: "studio@varelli.co.in",
  foundingDate: "2015",
  numberOfEmployees: {
    "@type": "QuantitativeValue",
    value: 25,
  },
  contactPoint: [
    {
      "@type": "ContactPoint",
      telephone: "+919964984695",
      contactType: "customer service",
      areaServed: "IN",
      availableLanguage: ["English", "Hindi"],
    },
    {
      "@type": "ContactPoint",
      telephone: "+919964984695",
      contactType: "sales",
      areaServed: "IN",
      availableLanguage: ["English"],
    },
  ],
  sameAs: [
    "https://instagram.com/varelliindia",
    "https://linkedin.com/company/varelli",
    "https://youtube.com/@varelli",
    "https://pinterest.com/varelliindia",
  ],
  areaServed: [
    { "@type": "City", name: "Bangalore" },
    { "@type": "City", name: "Mumbai" },
    { "@type": "City", name: "Delhi" },
    { "@type": "City", name: "Hyderabad" },
    { "@type": "City", name: "Chennai" },
    { "@type": "City", name: "Pune" },
    { "@type": "Country", name: "India" },
  ],
  knowsAbout: [
    "KNX home automation",
    "DALI-2 lighting control",
    "Dolby Atmos private cinema",
    "Zehnder ERV fresh air ventilation",
    "central vacuum systems",
    "luxury home security",
    "structured home networking",
    "Basalte keypads",
    "Sonus Faber speakers",
    "Ekinex plates",
    "luxury smart home design",
    "intelligent residential systems",
  ],
};
